# Exploratory Data Analysis (Day 02)

## import libraries and setup

In [101]:
#EDA (we have studied numpy and pandas so far...)
import numpy as np
import pandas as pd

#time stamp from last update (to maintain the record of dates)
import time as t
print('Last Update:  ', t.asctime())

#filter warnings (to ignore warnings from third parties libraries)
import warnings as w
w.filterwarnings('ignore')

#set random seed (setup random seed to ignore the redundancy in random data)
np.random.seed(42)  #indutrsial standard is 42

Last Update:   Sun Oct 11 10:57:36 2026

## Dataset

### Generate Data using numpy

In [102]:
names = np.char.add('std', np.arange(1,101).astype('str'))   # add characters with number range
names[:10]

array(['std1', 'std2', 'std3', 'std4', 'std5', 'std6', 'std7', 'std8',
       'std9', 'std10'], dtype='<U24')

In [103]:
ages = np.random.randint(18,40,100)
ages[:10]

array([24, 37, 32, 28, 25, 38, 24, 36, 28, 28], dtype=int32)

In [104]:
gender = np.random.choice(['Male', 'Female'],100)
gender[:10]

array(['Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
       'Male', 'Male', 'Female'], dtype='<U6')

In [105]:
# can be done with follwing two methods
# p1 = np.char.add(np.random.randint(10000, 100000, size=100).astype(str), '-')
# p2 = np.char.add(np.random.randint(10000000, 100000000, size=100).astype(str), '-')
# p3 = np.random.randint(0,10,100).astype(str)
# p4 = np.char.add(p1,p2)
# p5 = np.char.add(p4,p3)
# p5

p1 = np.random.randint(10000, 100000, size=100).astype(str)
p2 = np.random.randint(10000000, 100000000, size=100).astype(str)
p3 = np.random.randint(0,10,100).astype(str)

p1 = np.char.add(p1, '-')
p2 = np.char.add(p1, p2)
p3 = np.char.add('-',p3)

cnic = np.char.add(p2,p3)
cnic[:10]

array(['65016-27569187-3', '19474-64710375-3', '68053-64456147-0',
       '31959-88110973-7', '15530-49501026-2', '13748-43163773-6',
       '23545-21310552-1', '76199-41146082-1', '44766-31104792-6',
       '83530-31739356-5'], dtype='<U35')

In [106]:
# define marks
ml_100 = np.random.randint(20,101,100)
dl_100 = np.random.randint(10,101,100)
nlp_100 = np.random.randint(40,101,100)
eda_60 = np.random.randint(0,61,100)

### Introduce Null Values in Data

In [107]:
#randomly make five cnic null
cnic= cnic.astype(object)
cnic[np.random.randint(0,100,5)] = np.nan

### Convert it into Dictionary

In [108]:
data = {
    'Name' : names,
    'Age' : ages,
    'Gender': gender,
    'CNIC': cnic,
    'Machine Learning': ml_100,
    'Deep Learning': dl_100,
    'NLP': nlp_100,
    'EDA': eda_60
}

### Convert into Data Frame

In [109]:
df = pd.DataFrame(data)
df.head()

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
0,std1,24,Male,65016-27569187-3,51,14,57,10
1,std2,37,Male,19474-64710375-3,43,38,90,50
2,std3,32,Female,68053-64456147-0,31,46,44,38
3,std4,28,Male,31959-88110973-7,69,47,86,37
4,std5,25,Female,15530-49501026-2,54,92,64,59

### Save as CSV file

In [115]:
#index = False   "to remove any unnamed column in your data"
df.to_csv('students_records.csv', index= False)

In [116]:
df.shape

(100, 8)

In [117]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              100 non-null    str
 1   Age               100 non-null    int64
 2   Gender            100 non-null    str
 3   CNIC              95 non-null     str
 4   Machine Learning  100 non-null    int64
 5   Deep Learning     100 non-null    int64
 6   NLP               100 non-null    int64
 7   EDA               100 non-null    int64
dtypes: int64(5), str(3)
memory usage: 6.4 KB

## Exploratory Data Analysis

In [118]:
df = pd.read_csv('students_records.csv')

### Basic EDA

In [129]:
df.head()

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
0,std1,24,Male,65016-27569187-3,51,14,57,10
1,std2,37,Male,19474-64710375-3,43,38,90,50
2,std3,32,Female,68053-64456147-0,31,46,44,38
3,std4,28,Male,31959-88110973-7,69,47,86,37
4,std5,25,Female,15530-49501026-2,54,92,64,59

In [130]:
df.tail()

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
95,std96,34,Male,69040-40024204-4,61,38,54,26
96,std97,25,Male,22183-92008891-3,28,22,76,8
97,std98,20,Female,39299-58715257-7,69,55,60,25
98,std99,20,Male,22874-32268806-6,46,44,53,56
99,std100,18,Female,42711-16512440-1,85,15,41,46

In [131]:
df.columns

Index(['Name', 'Age', 'Gender', 'CNIC', 'Machine Learning', 'Deep Learning',
       'NLP', 'EDA'],
      dtype='str')

In [132]:
df.shape

(100, 8)

In [133]:
df.describe()

              Age  Machine Learning  Deep Learning         NLP         EDA
count  100.000000        100.000000     100.000000  100.000000  100.000000
mean    28.660000         57.370000      52.790000   68.810000   29.660000
std      6.390049         21.915658      25.804743   18.495806   18.106988
min     18.000000         21.000000      10.000000   40.000000    0.000000
25%     24.000000         37.750000      29.000000   52.750000   14.750000
50%     29.000000         55.000000      51.500000   69.000000   28.500000
75%     34.000000         76.250000      72.250000   86.250000   46.250000
max     39.000000        100.000000     100.000000   98.000000   60.000000

In [134]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              100 non-null    str
 1   Age               100 non-null    int64
 2   Gender            100 non-null    str
 3   CNIC              95 non-null     str
 4   Machine Learning  100 non-null    int64
 5   Deep Learning     100 non-null    int64
 6   NLP               100 non-null    int64
 7   EDA               100 non-null    int64
dtypes: int64(5), str(3)
memory usage: 6.4 KB

### Advance EDA

### Select columns fron dataset

In [141]:
df[df['Age']>35]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
1,std2,37,Male,19474-64710375-3,43,38,90,50
5,std6,38,Male,13748-43163773-6,52,17,41,33
7,std8,36,Male,76199-41146082-1,80,95,95,49
10,std11,38,Female,71087-21471761-2,31,98,98,29
14,std15,39,Male,56576-28877237-9,59,79,95,33
15,std16,38,Male,49353-56918818-9,93,40,72,51
20,std21,38,Female,99474-65403796-5,31,100,86,14
23,std24,39,Male,95616-15853584-0,54,28,60,54
30,std31,36,Male,97092-28298917-3,87,81,52,9
32,std33,37,Male,36309-87729132-6,94,48,73,16
35,std36,36,Male,80467-36365210-1,40,86,40,59
37,std38,38,Male,22688-37180308-2,29,72,87,23
45,std46,38,Male,90623-25900476-9,81,54,77,42
47,std48,37,Male,NaN,31,54,92,10
62,std63,39,Male,NaN,28,24,84,55
65,std66,39,Female,98614-24650271-9,97,63,40,31
77,std78,38,Female,26646-73967150-6,72,37,93,17
82,std83,38,Female,41616-70303849-9,24,67,51,20
94,std95,36,Male,16295-86294551-7,59,86,62,44

In [151]:
#show 1st two records of age
df['Age'][:2]

0    24
1    37
Name: Age, dtype: int64

In [147]:
#show age and gender (1st three only)
df[['Age', 'Gender']][:3]

   Age  Gender
0   24    Male
1   37    Male
2   32  Female

In [150]:
df.iloc[20:24]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
20,std21,38,Female,99474-65403796-5,31,100,86,14
21,std22,18,Female,33664-33508102-5,65,83,88,59
22,std23,29,Female,77172-19405634-4,21,99,50,29
23,std24,39,Male,95616-15853584-0,54,28,60,54

In [153]:
df.iloc[20]

Name                           std21
Age                               38
Gender                        Female
CNIC                99474-65403796-5
Machine Learning                  31
Deep Learning                    100
NLP                               86
EDA                               14
Name: 20, dtype: object

### Filter records from data

In [159]:
df[df['Age'] > 35]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
1,std2,37,Male,19474-64710375-3,43,38,90,50
5,std6,38,Male,13748-43163773-6,52,17,41,33
7,std8,36,Male,76199-41146082-1,80,95,95,49
10,std11,38,Female,71087-21471761-2,31,98,98,29
14,std15,39,Male,56576-28877237-9,59,79,95,33
15,std16,38,Male,49353-56918818-9,93,40,72,51
20,std21,38,Female,99474-65403796-5,31,100,86,14
23,std24,39,Male,95616-15853584-0,54,28,60,54
30,std31,36,Male,97092-28298917-3,87,81,52,9
32,std33,37,Male,36309-87729132-6,94,48,73,16
35,std36,36,Male,80467-36365210-1,40,86,40,59
37,std38,38,Male,22688-37180308-2,29,72,87,23
45,std46,38,Male,90623-25900476-9,81,54,77,42
47,std48,37,Male,NaN,31,54,92,10
62,std63,39,Male,NaN,28,24,84,55
65,std66,39,Female,98614-24650271-9,97,63,40,31
77,std78,38,Female,26646-73967150-6,72,37,93,17
82,std83,38,Female,41616-70303849-9,24,67,51,20
94,std95,36,Male,16295-86294551-7,59,86,62,44

In [158]:
df[(df['Age'] > 35) | (df['Age'] < 27)]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
0,std1,24,Male,65016-27569187-3,51,14,57,10
1,std2,37,Male,19474-64710375-3,43,38,90,50
4,std5,25,Female,15530-49501026-2,54,92,64,59
5,std6,38,Male,13748-43163773-6,52,17,41,33
6,std7,24,Female,23545-21310552-1,52,74,49,37
7,std8,36,Male,76199-41146082-1,80,95,95,49
10,std11,38,Female,71087-21471761-2,31,98,98,29
11,std12,21,Female,78840-29576703-8,86,54,84,14
12,std13,25,Male,64384-85092305-9,84,13,44,26
13,std14,20,Female,61005-82429249-5,52,45,94,50
14,std15,39,Male,56576-28877237-9,59,79,95,33
15,std16,38,Male,49353-56918818-9,93,40,72,51
16,std17,19,Female,72003-33705256-5,62,28,93,56
18,std19,23,Male,62733-87633091-3,48,63,57,32
19,std20,19,Male,75318-89452960-9,32,48,71,23
20,std21,38,Female,99474-65403796-5,31,100,86,14
21,std22,18,Female,33664-33508102-5,65,83,88,59
23,std24,39,Male,95616-15853584-0,54,28,60,54
30,std31,36,Male,97092-28298917-3,87,81,52,9
32,std33,37,Male,36309-87729132-6,94,48,73,16
33,std34,20,Female,97455-87275698-7,48,10,80,9
34,std35,22,Male,73734-83214389-3,55,12,74,16
35,std36,36,Male,80467-36365210-1,40,86,40,59
36,std37,24,Female,62662-68245345-9,55,71,60,19
37,std38,38,Male,22688-37180308-2,29,72,87,23
38,std39,26,Male,35342-21326237-0,92,34,94,4
39,std40,24,Male,47157-96343264-7,43,65,45,33
41,std42,21,Male,62083-64434670-9,68,47,56,52
44,std45,26,Female,44698-59114107-4,42,53,44,42
45,std46,38,Male,90623-25900476-9,81,54,77,42
46,std47,19,Male,32671-50820227-4,56,41,42,47
47,std48,37,Male,NaN,31,54,92,10
49,std50,24,Male,96202-63059071-4,32,56,76,46
51,std52,25,Female,25708-22707035-9,49,89,76,22
53,std54,20,Female,12811-80560220-0,81,84,49,15
56,std57,21,Male,44754-76385640-8,38,29,60,53
58,std59,25,Male,12911-88384476-4,31,27,48,7
59,std60,21,Male,77270-52058334-0,80,56,85,3
60,std61,19,Male,93763-59742523-6,38,58,40,39
61,std62,23,Male,18680-49769056-4,95,23,90,3
62,std63,39,Male,NaN,28,24,84,55
64,std65,21,Male,81295-53369428-2,47,10,43,2
65,std66,39,Female,98614-24650271-9,97,63,40,31
68,std69,19,Male,11802-28992383-5,88,96,71,28
70,std71,21,Female,83656-66877183-4,44,84,67,49
74,std75,25,Female,95981-42474983-9,35,81,65,18
76,std77,25,Male,40306-24716695-4,58,33,73,4
77,std78,38,Female,26646-73967150-6,72,37,93,17
82,std83,38,Female,41616-70303849-9,24,67,51,20
84,std85,26,Female,39855-53167705-5,94,59,93,0
87,std88,18,Female,53016-59913224-1,28,73,69,11
88,std89,24,Male,17400-74356138-3,93,36,69,25
89,std90,26,Female,52642-77607727-9,77,72,98,45
90,std91,18,Male,25151-63007836-9,36,26,96,33
92,std93,25,Female,76690-68114585-9,65,42,87,13
94,std95,36,Male,16295-86294551-7,59,86,62,44
96,std97,25,Male,22183-92008891-3,28,22,76,8
97,std98,20,Female,39299-58715257-7,69,55,60,25
98,std99,20,Male,22874-32268806-6,46,44,53,56
99,std100,18,Female,42711-16512440-1,85,15,41,46

In [162]:
df[df['NLP']<43]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
5,std6,38,Male,13748-43163773-6,52,17,41,33
17,std18,29,Female,93211-94504547-0,63,70,40,37
35,std36,36,Male,80467-36365210-1,40,86,40,59
46,std47,19,Male,32671-50820227-4,56,41,42,47
60,std61,19,Male,93763-59742523-6,38,58,40,39
65,std66,39,Female,98614-24650271-9,97,63,40,31
79,std80,30,Female,26371-74785345-0,77,45,42,41
83,std84,30,Female,30932-20192257-9,54,69,40,5
99,std100,18,Female,42711-16512440-1,85,15,41,46

In [164]:
df[df['Machine Learning']>90]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
15,std16,38,Male,49353-56918818-9,93,40,72,51
24,std25,29,Male,36736-34947744-7,100,48,65,41
27,std28,33,Male,17392-58673237-6,93,22,98,4
32,std33,37,Male,36309-87729132-6,94,48,73,16
38,std39,26,Male,35342-21326237-0,92,34,94,4
61,std62,23,Male,18680-49769056-4,95,23,90,3
65,std66,39,Female,98614-24650271-9,97,63,40,31
84,std85,26,Female,39855-53167705-5,94,59,93,0
86,std87,30,Female,82694-50869792-3,95,50,44,40
88,std89,24,Male,17400-74356138-3,93,36,69,25

### Value Count (Gender)

In [166]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [167]:
df['Gender'].value_counts()

Gender
Male      56
Female    44
Name: count, dtype: int64

#find students with same marks

In [176]:
(df['EDA'].value_counts()>1).sum()

np.int64(29)

In [180]:
df['EDA'].value_counts()

EDA
50    5
33    5
4     4
10    3
37    3
59    3
26    3
56    3
16    3
3     3
25    3
49    2
17    2
29    2
14    2
23    2
54    2
41    2
28    2
9     2
55    2
5     2
42    2
46    2
15    2
2     2
31    2
60    2
20    2
38    1
51    1
32    1
19    1
52    1
1     1
12    1
47    1
22    1
30    1
53    1
7     1
39    1
24    1
57    1
18    1
27    1
21    1
0     1
40    1
11    1
45    1
48    1
13    1
44    1
8     1
Name: count, dtype: int64

In [179]:
df['EDA'].unique()

array([10, 50, 38, 37, 59, 33, 49, 17, 29, 14, 26, 51, 56, 32, 23, 54, 41,
       16,  4, 28,  3,  9, 55, 19,  5, 52,  1, 12, 42, 47, 46, 22, 15, 30,
       53,  7, 39, 24,  2, 31, 60, 57, 18, 20, 27, 21,  0, 40, 11, 25, 45,
       48, 13, 44,  8])

In [181]:
df['Age'].value_counts()

Age
32    8
25    8
38    8
29    7
24    6
21    6
20    5
19    5
35    5
28    4
36    4
39    4
18    4
26    4
31    4
37    3
34    3
27    3
33    3
30    3
23    2
22    1
Name: count, dtype: int64

### Handling Null Values

In [182]:
df.isna()

     Name    Age  Gender   CNIC  Machine Learning  Deep Learning    NLP    EDA
0   False  False   False  False             False          False  False  False
1   False  False   False  False             False          False  False  False
2   False  False   False  False             False          False  False  False
3   False  False   False  False             False          False  False  False
4   False  False   False  False             False          False  False  False
..    ...    ...     ...    ...               ...            ...    ...    ...
95  False  False   False  False             False          False  False  False
96  False  False   False  False             False          False  False  False
97  False  False   False  False             False          False  False  False
98  False  False   False  False             False          False  False  False
99  False  False   False  False             False          False  False  False

[100 rows x 8 columns]

In [183]:
df.isna().sum()

Name                0
Age                 0
Gender              0
CNIC                5
Machine Learning    0
Deep Learning       0
NLP                 0
EDA                 0
dtype: int64

In [184]:
#inplace =True saves permanently
df.dropna(inplace=True)

In [185]:
df.isna().sum()

Name                0
Age                 0
Gender              0
CNIC                0
Machine Learning    0
Deep Learning       0
NLP                 0
EDA                 0
dtype: int64

In [186]:
df.isna().sum().sum()

np.int64(0)

In [187]:
df.shape

(95, 8)

### Feature Engineering

In [190]:
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA
0,std1,24,Male,65016-27569187-3,51,14,57,10

# as there is no full marks then add column

In [191]:
df['Obtained Marks'] = df['Machine Learning'] + df['Deep Learning'] + df['NLP']+df['EDA']

In [192]:
df.head(2)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA,Obtained Marks
0,std1,24,Male,65016-27569187-3,51,14,57,10,132
1,std2,37,Male,19474-64710375-3,43,38,90,50,221

In [194]:
df['Percentage'] = (df['Obtained Marks']*100/360).round(2)

In [195]:
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA,Obtained Marks,Percentage
0,std1,24,Male,65016-27569187-3,51,14,57,10,132,36.67

In [196]:
df['Average Marks'] = (df['Obtained Marks']/4).round(2)

In [197]:
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA,Obtained Marks,Percentage,Average Marks
0,std1,24,Male,65016-27569187-3,51,14,57,10,132,36.67,33.0

#method1

In [202]:
df['Status'] = df["Percentage"].apply(lambda x: 'passed' if x>50 else "Failed")

In [203]:
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA,Obtained Marks,Percentage,Average Marks,Status
0,std1,24,Male,65016-27569187-3,51,14,57,10,132,36.67,33.0,Failed

#method2

In [204]:
def check_status(x):
    if (x>50):
        return "Passed"
    else: 
        return "Failed"

In [205]:
df['Status'] = df['Percentage'].apply(check_status)

In [206]:
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,NLP,EDA,Obtained Marks,Percentage,Average Marks,Status
0,std1,24,Male,65016-27569187-3,51,14,57,10,132,36.67,33.0,Failed

In [208]:
df['Deep Learning'].max()

np.int64(100)

# Avg marks w.r.t gender in subject (Deep Learning)

In [210]:
df.groupby('Gender')['Deep Learning'].mean()

Gender
Female    59.465116
Male      47.807692
Name: Deep Learning, dtype: float64

In [213]:
df.groupby('Gender')['Deep Learning'].max()

Gender
Female    100
Male       96
Name: Deep Learning, dtype: int64

In [215]:
df.groupby('Gender')['Deep Learning'].median()

Gender
Female    66.0
Male      45.5
Name: Deep Learning, dtype: float64

In [217]:
df.groupby('Gender')['Deep Learning'].sum()

Gender
Female    2557
Male      2486
Name: Deep Learning, dtype: int64

In [218]:
df.groupby('Gender')['Deep Learning'].min()

Gender
Female    10
Male      10
Name: Deep Learning, dtype: int64

In [219]:
df.groupby('Gender')['Deep Learning'].count()

Gender
Female    43
Male      52
Name: Deep Learning, dtype: int64

In [220]:
df.groupby('Gender')['Deep Learning'].size()

Gender
Female    43
Male      52
Name: Deep Learning, dtype: int64

In [221]:
df.groupby('Gender')['Deep Learning'].nunique()

Gender
Female    34
Male      41
Name: Deep Learning, dtype: int64

In [222]:
df.size

1140

In [224]:
df.shape

(95, 12)

### Save the Updated CSV file

In [ ]:
df.to_csv('Students_Records_Updated')